# Generated by Django 4.1.2 on 2022-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_alter_song_date_released'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='Song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='Artiste',
        ),
        migrations.AlterField(
            model_name='artiste',
            name='age',
            field=models.IntegerField(),
        ),
    ]
